#!/bin/sh /etc/rc.common
START=89
USE_PROCD=1

validate_connection_section() {
	uci_validate_section 'private-internet-access' connection "${1}" \
		'username:string' \
		'password:string' \
		'server:string' \
		'name:string' \
		'enabled:bool'
}

service_triggers() {
	procd_add_reload_trigger 'private-internet-access'
	procd_open_trigger
	procd_add_config_trigger "config.change" "private-internet-access" /etc/init.d/private-internet-access reload
	procd_close_trigger

	procd_open_validate
	validate_connection_section
	procd_close_validate
}

config_pia() {
	local cfg="$1"
	config_get cfg_server "$cfg" 'server' ''
	config_get cfg_interfacename "$cfg" 'name' ''
	config_get cfg_username "$cfg" 'username' ''
	config_get cfg_password "$cfg" 'password' ''
	config_get cfg_routingtable "$cfg" 'routing_table' ''
	config_get cfg_enabled "$cfg" 'enabled' '0'
	if [ "$cfg_enabled" == "1" ] && [ ! -z "$cfg_server" ] && [ ! -z "$cfg_username" ] && [ ! -z "$cfg_password" ] ; then
		procd_open_instance
		procd_set_param command /usr/bin/lua /usr/lib/pia/apply-pia.lua spawn "$cfg" "$(echo "$cfg_enabled $cfg_server $cfg_interfacename $cfg_username $cfg_password $cfg_routingtable" | md5sum | cut -d' ' -f1)"
		procd_set_param respawn
		procd_close_instance
	fi
}

start_service() {
	ubus -t 90 wait_for network.interface 2>/dev/null
	config_load private-internet-access
	config_foreach config_pia connection
}
