#!/bin/sh

while [ ! -z "$(uci -q get ucitrack.@policy-routing[-1] 2>/dev/null)" ] ; do
	uci -q delete ucitrack.@policy-routing[-1]
done

while [ ! -z "$(uci -q get ucitrack.@firewall[-1].affects 2>/dev/null | awk '/policy-routing/')" ] ; do
	uci -q del_list ucitrack.@firewall[-1].affects='policy-routing'
done

uci -q batch <<-EOF >/dev/null
	add ucitrack policy-routing
	set ucitrack.@policy-routing[-1].init='policy-routing'
	add_list ucitrack.@firewall[-1].affects='policy-routing'
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
